Feature/#61 brand api
f-lab-edu/resell-platform pull request #64
Opened 2022-08-23 04:30 UTC by jvnlee

## PR 체크 리스트
아래 요구사항 중 만족한 것들을 체크해주세요:

- [ v] 커밋 메세지가 가이드라인을 따르는지 체크 https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ v] 변경 사항에 대한 테스트를 작성했는지 (for bug fixes / features)
- [ ] 문서가 추가되거나 업데이트 됐는지 (for bug fixes / features)

## PR 유형
해당 PR에 포함된 변경 사항에 'o'를 그려주세요: 

- [ ] 버그 해결(Bugfix)
- [ o ] 기능 추가(Feature)
- [ ] 코드 스타일(Code style update ex.ormatting, local variables)
- [ ] 리팩토링(Refactoring ex.no functional changes, no api changes)
- [ ] 빌드 관련된 변경(Build related changes)
- [ ] CI 관련된 변경(CI related changes)
- [ ] 문서 내용 변경(Documentation content changes)
- [ ] 기타... Please describe:

## 문제가 됐던 기능에 대해 설명해주세요(What is the current behavior?)

Issue Number: #61 

## 새로운 기능에 대해 설명해주세요(What is the new behavior?)

거래 API 작업을 하기 앞서, 거래 엔티티를 다루는데 필요한 브랜드 관련 API (CRUD)에 대한 코드입니다. 브랜드를 조회하는 것을 제외한 생성, 수정, 삭제는 관리자(ADMIN)만의 권한이기 때문에 관리자 권한이 있는 사용자만 해당 API를 사용할 수 있습니다.

## 해당 PR로 인해 프로젝트의 많은 부분이 변경되나요?(Does this PR introduce a breaking change?)

- [ ] Yes
- [ v ] No

## 기타 정보(Other information)

2022-08-25 10:45 UTC, michaelkimm reviewed
전체적으로 가독성 있게 코드를 작성하셨군요! 제가 배울 점이 많은 듯 합니다.

피드백 남긴 것 이외에 두가지 추가로 요청드립니다!

1. 커밋 제목 뿐 아니라 커밋 메세지도 작성 부탁드려요!
2. PR 날릴 시, Reviewer 뿐 아니라 Assignees, Label, Project등 다른 사항들도 설정해주세요! 설정 해주시면 다른 팀원분들이 과거 pr 찾아보기가 편합니다:)

2022-08-25 10:45 UTC, michaelkimm commented on src/test/java/flab/resellPlatform/repository/brand/MyBatisBrandRepositoryTest.java
> +                .build();
brandEntity1 객체는 매 테스트마다 새로 만들게되어 코드가 중복 되는 듯 하네요.
@BeforeEach 기능이 붙은 setUp 함수를 만들어서 중복을 제거할 수 있지 않을까요?

2022-08-25 10:45 UTC, michaelkimm commented on src/test/java/flab/resellPlatform/repository/brand/MyBatisBrandRepositoryTest.java
> +    void delete() {
브랜드 정보 삭제는 왜 테스트가 없나요?

2022-08-25 10:45 UTC, michaelkimm commented on src/main/java/flab/resellPlatform/controller/brand/BrandController.java
> +        }
흠 코드 구현 취향 차이겠지만, 아래 코드가 중복되는 듯해 보이네요. `"brand.update.success"`를 변수화 하는게 낫지 않을까요?
`StandardResponse.builder()
                    .message(messageSourceAccessor.getMessage("brand.update.failure"))
                    .build()`

2022-08-25 10:45 UTC, michaelkimm commented on src/main/java/flab/resellPlatform/controller/brand/BrandController.java
> +                    .message(messageSourceAccessor.getMessage("brand.delete.failure"))
여기서 등장하는 코드 중복 또한 같은 의견입니다.

2022-08-25 10:45 UTC, michaelkimm commented on src/main/java/flab/resellPlatform/service/brand/BrandService.java
> +    Optional<List<BrandEntity>> viewAllBrands();
Service 코드 내에서 List<BrandEntity>를 Optional Null로 반환해야할 필요가 있을 때 예외를 던져주는게 낫지 않을까요? 

이유1 : 해당 방식을 사용하면 Controller 입장에선 올바른 응답이 오는 가정 하에 코드를 짤 수 있어서 코드가 깔끔해질듯 합니다. 

이유2 : UserController도 해당 방식을 사용하고 있어요. 일관된 구현이 되면 이해하기 더욱 좋아질 듯 하네요!

이유3 : @f-lab-jason 님께서 해당 문제에 대해 이전 PR에서 피드백 해주셨었습니다.
피드백 링크 : https://github.com/f-lab-edu/resell-platform/pull/56#discussion_r944129902

2022-08-28 23:36 UTC, f-lab-jason requested changes

2022-08-28 23:36 UTC, f-lab-jason commented on src/main/java/flab/resellPlatform/controller/brand/BrandController.java
> +                .data(Map.of("brands", brandService.viewAllBrands().orElseThrow()))
`..orElseThrow()`가 호출이 될 수 있는 케이스가 있나요?
`BrandServiceImpl`에서 `return Optional.of(brandRepository.findAll());`로 돌려주면 `brandRepository.findAll()`은 최소한 빈 리스트를 돌려줄 것이고 null을 리턴받는 케이스는 없을것으로 보이는데 Optional로 감싸는건 의미가 없어보이네요.

2022-08-28 23:36 UTC, f-lab-jason commented on src/main/java/flab/resellPlatform/controller/brand/BrandController.java
> +        }
민석님 말씀처럼 단순하게 메세지만 출력할 업데이트라면 하나로 모으는게 좋겠네요.

저라면 아래와 같은 형태를 선호할 것 같습니다.
```
@PutMapping("/{brandId}")
@PreAuthorize(Role.ADMIN)
public StandardResponse updateBrand(@PathVariable Long brandId, BrandDTO brandDTO) {
    return buildPlainResponse(brandService.updateBrand(brandId, brandDTO));
}

@DeleteMapping("/{brandId}")
@PreAuthorize(Role.ADMIN)
public StandardResponse deleteBrand(@PathVariable Long brandId) {
    return buildPlainResponse(brandService.deleteBrand(brandId));
}

private StandardResponse buildPlainResponse(boolean isSucceeded) {
    return StandardResponse.builder()
            .message(messageSourceAccessor.getMessage(
                    isSucceeded ? "brand.update.success" : "brand.update.failure"))
            .build();
}
```

2022-08-28 23:36 UTC, f-lab-jason commented on src/main/java/flab/resellPlatform/repository/brand/BrandMapper.java
> +    List<BrandEntity> findAll();
(nit) 추후에 paging을 고려할 생각은 있으신가요? 브랜드 양이 많아지면 비용이 너무 비싼 쿼리가 될 것 같네요

2022-08-28 23:36 UTC, f-lab-jason commented on src/main/java/flab/resellPlatform/repository/brand/MyBatisBrandRepository.java
> +        } catch (SQLException e) {
실제로 중복된 name을 넣었을 때 SQLException을 던지나요?
제 기억엔 IntegrityConstraintViolationException같은게 나왔던 것 같은데..

2022-08-28 23:36 UTC, f-lab-jason commented on src/main/java/flab/resellPlatform/service/brand/BrandServiceImpl.java
> +        brandRepository.delete(id);
제 기억에 mapper에서 annotation delete를 쓸 때 리턴값으로 boolean이나 int를 받을 수 있을거예요. 
그럼 아래 findById 없이 delete만으로 원하는 작업을 할 수 있을거라고 생각되는데 찾아보시면 좋겠습니다.

2022-08-28 23:36 UTC, f-lab-jason commented on src/main/java/flab/resellPlatform/service/brand/BrandServiceImpl.java
> +        return brandDTO;
리턴하는 값은 입력으로 받은 brandDTO가 아닌 brandRepository.save(brandEntity)의 결과값으로 받은 entity를 넘겨주세요.

2022-08-28 23:36 UTC, f-lab-jason commented on src/main/java/flab/resellPlatform/controller/brand/BrandController.java
> +        return standardResponse;
(nit) 그냥 간단하게 빌드하는것 자체를 리턴해주면 좋겠어요 🙂 
또한 보통 add같은 operation은 add된 객체를 리턴해주는 경우가 많은데 고려해보시면 좋겠네요. (id등이 포함된)
```
        return StandardResponse.builder()
                .message(messageSourceAccessor.getMessage("brand.add.success"))
                .build();
```

2022-08-28 23:36 UTC, f-lab-jason commented on src/test/java/flab/resellPlatform/controller/brand/BrandControllerTest.java
> +        resultActions.andExpect(status().is2xxSuccessful());
(nit) 만약 컨트롤러에 리뷰 남겨드린 것처럼 생성된 entity를 리턴한다면 그 값을 input과 비교하는 부분이 있으면 좋겠네요.

2022-08-28 23:36 UTC, f-lab-jason commented on src/test/java/flab/resellPlatform/controller/brand/BrandControllerTest.java
> +//        resultActions.andExpect(status().is2xxSuccessful());
(nit) 필요없는 주석분은 삭제해주세요!

2022-08-28 23:36 UTC, f-lab-jason commented on src/test/java/flab/resellPlatform/controller/brand/BrandControllerTest.java
> +class BrandControllerTest {
실패 케이스들도 테스트가 있으면 좋겠습니다.

2022-08-28 23:36 UTC, f-lab-jason commented on src/test/java/flab/resellPlatform/service/brand/BrandServiceImplTest.java
> +class BrandServiceImplTest {
각 테스트에서 `brandRepository`의 메소드가 호출되었는지 verify하는 코드도 추가해주세요!

2023-01-27 13:24 UTC, closed without merging